# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: "nuget"
    directory: "/Sources/"                    # Path to '*.sln' directory
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    commit-message:
      prefix: "build"
      include: "scope"
    ignore:
      - dependency-name: "Microsoft.AspNetCore.Http.Features"
        versions: ["5.*"]                     # This package [version 5] has been deprecated
    groups:
      Microsoft:
        patterns:
          - "Microsoft.*"
      System:
        patterns:
          - "System.*"
      Tests:
        patterns:
          - "NUnit*"
          - "Moq*"

  - package-ecosystem: "gitsubmodule"
    directory: "/"                            # Path to '.gitmodules' directory
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      submodules:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"                            # Workflow files stored in the default location
    schedule:
      interval: "monthly"
    labels:
      - "github-actions"
      - "dependencies"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      Common-actions:
        patterns:
          - "actions/*"
      Finebits-actions:
        patterns:
          - "finebits/*"
      GitHub-actions:
        patterns:
          - "github/*"
